services:
  parser:
    build: .
    volumes:
      - ./pizzas.db:/app/pizzas.db
    working_dir: /app
    command: python parse.py
    restart: "no"

  pizza_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - parser  # Указываем, что parser должен завершить работу
    command: python app.py
    restart: always
