version: "3.8"

services:
  parser:
    build: .
    volumes:
      - .:/app
      - ./pizzas.db:/app/pizzas.db
    command: python parse.py
    restart: "no"

  pizza_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
      - ./pizzas.db:/app/pizzas.db
    command: python app.py
    restart: always
