services:
  parser:
    build: .
    volumes:
      - .:/app
    command: python parse.py
    restart: "no"

  pizza_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - parser
    command: python app.py
    restart: always
